common:
    lid_topic:  "/hori/hesai/pandar"
    lid_topic_vert:  "/vert/hesai/pandar"
    imu_topic:  "/imu/data"
    time_sync_en: false         # ONLY turn on when external time synchronization is really not possible
    time_offset_lidar_to_imu: -0.015170# Time offset between lidar and IMU calibrated by other algorithms, e.g. LI-Init (can be found in README).
                                  # This param will take effect no matter what time_sync_en is. So if the time offset is not known exactly, please set as 0.0

preprocess:
    lidar_type: 5                # Hesai PandarXT
    scan_line: 32
    scan_rate: 10                # only need to be set for velodyne, unit: Hz,
    blind: 0.2
    pre_filter: false             # added by jxf @2023.6.20 filter the bleeding point
    noise_threshold: 0.007

mapping:
    acc_cov: 0.1
    gyr_cov: 0.1
    b_acc_cov: 0.0001
    b_gyr_cov: 0.0001
    fov_degree:    180
    det_range:     100.0
    extrinsic_est_en:  true      # true: enable the online estimation of IMU-LiDAR extrinsic,
    extrinsic_T: [-0.026893, -0.000250, 0.053052]
    extrinsic_R: [ 0.999938,-0.005749,-0.009530, 
                   0.005699,0.999970,-0.005234,
                   0.009560,0.005179,0.999941]
    extrinsic_V2H: [-0.99774054,-0.03961016,0.05426564,-0.0021799,
-0.05004051,-0.1008282,-0.99364444,-0.41172648,
0.04482938,-0.99411489,0.0986187,-0.86626278,
0,0,0,1]


publish:
    path_en:  true
    scan_publish_en:  true       # false: close all the point cloud output
    dense_publish_en: false       # false: low down the points number in a global-frame point clouds scan.
    scan_bodyframe_pub_en: true  # true: output the point cloud scans in IMU-body-frame

pcd_save:
    pcd_save_en: false
    interval: 1                 # how many LiDAR frames saved in each pcd file; 
                                 # -1 : all frames will be saved in ONE pcd file, may lead to memory crash when having too much frames.

pc_reg:
    dual_LiDAR_en: true

loop:                          # added by jxf @2023.8.29 add SLAM loop
    loop_en: true
    loopInterval: 30    # loop  scale of the time >30s
    loopDistance: 2     #loop  scale of the distance <2m
    icpMatchScoreThre: 0.05      #the more higher scores,the  wrong loop
    
